### ISSUE TITLE
Using assembly data other than IDBA

### ISSUE THREAD

**Issue by mhyleung** [minoh0201/MetaCompare#3]
Dear MetaCompare

I was wondering if we can use any assembly methods for MetaCompare (e.g. megahit/metaspades), especially if the input for MetaCompare is simply an assembly.fasta file and prodigal outputs.

Thanks

Marc

**Comment by minoh0201** [comment]
Technically, it will work but various parameters of MetaCompare were tuned towards IDBA-UD output so it can not be guaranteed whether the result makes sense.
