### ISSUE TITLE
Discordance between MetaCompare and BLAST

### ISSUE THREAD

**Issue by LJauregi** [minoh0201/MetaCompare#4]
Dear @minoh0201,

The MetaCompare output tells us a specific number of ARGs, MGEs and pathogens. But when we compare the MetaCompare results with the BLAST files, a discordance is found in the detected number of ARGs, MGEs and pathogens. In the BLAST files we find a higher number of the three elements mentioned above. We know that for (i) ARGs, the results are filtered based on E-value < 1E-10, Identity >60%, and Minimum alignment length > 25 amino acids, (ii) MGEs, E-value < 1E-10, Identity >60% and 90% coverage of the MGE reference, and (iii) pathogens, E-value <1e-10, Identity >60%, Minimum alignment length >150 bps.
Is there any way to filter the results in the BLAST files so that the detected number of the three elements matches that of MetaCompare?

Thanks in advance,
Leire​

**Comment by minoh0201** [comment]
The output of MetaCompare tells you the number of scaffolds having ARGs, not the number of ARG alignments. Suppose a certain scaffold (contig) has three ARGs identified by BLAST. MetaCompare increases nARG count by one, not by three. Likewise, another scaffold having multiple ARG, multiple MGE, and multiple pathogen alignments is still being considered to increase nARG_MGE_PAT by 1.

**Comment by LJauregi** [comment]
Thank you very much for your response.  

As you indicate, the number of contigs coincides in the two outputs for ARGs and Pathogens. In the case of the MGEs, how could we filter out less than 90% coverage of the MGE reference to the BLASTN file (ACLAME db)? Is there a quick formula to filter the results? 

Thanks in advance,
Leire

**Comment by minoh0201** [comment]
You can use "Len_aclame.txt" to get the length of MGE references. Also, I recommend checking out "metacmp.py" line 108-119.
