### ISSUE TITLE
cannot download database in bench.cs.vt.edu? Is it a intranet?

### ISSUE THREAD

**Issue by kingtom2016** [minoh0201/metacompare#5]
Is bench.cs.vt.edu a intranet? and cannot be accessed by a public user?
The bench.cs.vt.edu cannot be opened even if I switch a US net node or use --no-check-certificate option.  Could you provide another link for downloading or tell me how can I access the bench.cs.vt.edu.

**Comment by minoh0201** [comment]
The link was broken for a while, but now it is serving as it had been. Please try again.

**Comment by Sizhe-Chen** [comment]
Hi, thanks for the attention, but the link seems to be broken again...

**Comment by shaodongyan** [comment]
> Is bench.cs.vt.edu a intranet? and cannot be accessed by a public user? The bench.cs.vt.edu cannot be opened even if I switch a US net node or use --no-check-certificate option. Could you provide another link for downloading or tell me how can I access the bench.cs.vt.edu.

Hello, Jintao @kingtom2016 Have you downloaded the database?

**Comment by SelfShubham** [comment]
hello. can anyone can help me to download the database.
