### ISSUE TITLE
contigs--megahit assembly?could I use the software?

### ISSUE THREAD

**Issue by CXang** [minoh0201/metacompare#6]
according to the useage,I found that the input contigs must be assembly by IDBA-UD,but now ,I use the software megahit to assembly ,so could I use the software?

**Comment by minoh0201** [comment]
You can proceed with megahit but please be aware that there could be assembler bias if you compare samples with different assemblers. The score scale derived from IDBA-UD could be different from that of megahit. As long as you compare samples only processed with Megahit, it should be fine.

**Comment by CXang** [comment]
> You can proceed with megahit but please be aware that there could be assembler bias if you compare samples with different assemblers. The score scale derived from IDBA-UD could be different from that of megahit. As long as you compare samples only processed with Megahit, it should be fine.

Thank you so much~~~glad to have your reply！
