### ISSUE TITLE
using different programs initially

### ISSUE THREAD

**Issue by bioforkgithub** [minoh0201/metacompare#7]
I want to know if we can use
1. Trimgalore instead of tRIMMOMATIC
2. MEGAHIT INSTEAD OF IDBA
3. And then Prodial
Will the program work on a PC to do the work?

**Comment by bioforkgithub** [comment]
(metacompare) [a40540@styx MetaCompare]$ python3 metacmp.py -c S1.fa -g S1_genes.fa
check file path:
/gpfs/gpfs0/prosjekt/.prosjekt2/15719-Res-Marine/softwares/MetaCompare
Running blastn on ACLAME
blastn: error while loading shared libraries: libnsl.so.1: cannot open shared object file: No such file or directory
Running blastx on CARD
blastx: error while loading shared libraries: libnsl.so.1: cannot open shared object file: No such file or directory
Running blastn on PATRIC
blastn: error while loading shared libraries: libnsl.so.1: cannot open shared object file: No such file or directory
Reading files..
Computing resistome risk score..
Traceback (most recent call last):
  File "/gpfs/gpfs0/prosjekt/.prosjekt2/15719-Res-Marine/softwares/MetaCompare/metacmp.py", line 98, in <module>
    if not os.path.getsize(os.getcwd()+"/"+acc_name) > 0:
  File "/home/a40540/anaconda3/envs/metacompare/lib/python3.10/genericpath.py", line 50, in getsize
    return os.stat(filename).st_size
FileNotFoundError: [Errno 2] No such file or directory: '/gpfs/gpfs0/prosjekt/.prosjekt2/15719-Res-Marine/softwares/MetaCompare/S1_ACLAME.txt'


This is the run that I tried with the test files provided on the github page. It gives an error

**Comment by bioforkgithub** [comment]
Tried everything. It works on assembly from megahit and trimgalore and prodigal. There was a problem with anaconda blast files. Binaries from NCBI solved the problem.

**Comment by shaodongyan** [comment]
@bioforkgithub Hello! I hope this message finds you well. I am writing to kindly request your assistance. I am very interested in accessing the database of MetaCompare software, but unfortunately, I do not currently have access to it. I understand that you may have the privilege of accessing or owning this database, and I was wondering if you would be willing to share a copy with me. Your generosity in granting me access would be greatly appreciated, and I would be sincerely grateful for your help.

If there is any additional information you require or if you have any questions, please feel free to let me know. Thank you very much for your time and assistance.

Warmest regards,Dongyan
